import { execFileSync } from "node:child_process"
import { existsSync, mkdirSync, writeFileSync } from "node:fs"
import { homedir } from "node:os"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const packageDir = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const contractsDir = resolve(packageDir, "../../contracts")
const abiDir = resolve(packageDir, "src/abi")
const forge = process.env.FORGE_BIN || (existsSync(resolve(homedir(), ".foundry/bin/forge")) ? resolve(homedir(), ".foundry/bin/forge") : "forge")

const contracts = [
  ["EscrowFactory", "src/EscrowFactory.sol:EscrowFactory"],
  ["MilestoneEscrow", "src/MilestoneEscrow.sol:MilestoneEscrow"],
  ["MockUSDT", "src/testnet/MockUSDT.sol:MockUSDT"],
]

mkdirSync(abiDir, { recursive: true })

for (const [name, target] of contracts) {
  const abi = execFileSync(forge, ["inspect", target, "abi", "--json"], {
    cwd: contractsDir,
    encoding: "utf8",
  }).trim()
  writeFileSync(resolve(abiDir, `${name}.ts`), `// Generated by pnpm contracts:export. Do not edit.\nexport const ${name}Abi = ${abi} as const\n`)
}
