import { RiAddLine, RiCheckLine, RiMessage2Line, RiRefreshLine, RiShieldCheckLine } from "@remixicon/react"
import { useState } from "react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Amount, WalletAddress } from "@/components/ui/financial"
import { PageHeader } from "@/components/ui/page"

const wallets = {
  client: { name: "Alice · Client", address: "0x1111111111111111111111111111111111111111" },
  provider: { name: "Bruno · Provider", address: "0x2222222222222222222222222222222222222222" },
  arbiter: { name: "Cora · Arbiter", address: "0x3333333333333333333333333333333333333333" },
} as const
type Role = keyof typeof wallets
type Status = "draft" | "funded" | "delivered" | "disputed" | "approved" | "resolved"
type DemoState = { created: boolean; status: Status; title: string; amounts: string[]; currentMilestone: number; note: string; chats: string[] }
const fresh = (): DemoState => ({ created: false, status: "draft", title: "Website redesign", amounts: ["1200", "1200"], currentMilestone: 0, note: "", chats: ["Alice: Welcome — the brief and delivery timeline are ready."] })
const statusLabel: Record<Status, string> = { draft: "Awaiting funding", funded: "Active", delivered: "Awaiting approval", disputed: "In dispute", approved: "Completed", resolved: "Resolved" }
const storageKey = "milestonepay-full-demo"
const load = () => { try { const value = JSON.parse(localStorage.getItem(storageKey) || "") as Partial<DemoState> & { amount?: string }; return Array.isArray(value.amounts) ? { ...fresh(), ...value } : { ...fresh(), ...value, amounts: [value.amount || "2400"] } } catch { return fresh() } }

export function Demo() {
  const [role, setRole] = useState<Role>(() => (localStorage.getItem("milestonepay-demo-role") as Role) || "client")
  const [demo, setDemo] = useState<DemoState>(load)
  const [chat, setChat] = useState("")
  const save = (next: DemoState) => { localStorage.setItem(storageKey, JSON.stringify(next)); setDemo(next) }
  const selectRole = (value: Role) => { localStorage.setItem("milestonepay-demo-role", value); setRole(value) }
  const update = (patch: Partial<DemoState>) => save({ ...demo, ...patch })
  const sendChat = () => { if (!chat.trim()) return; update({ chats: [...demo.chats, `${wallets[role].name.split(" ·")[0]}: ${chat.trim()}`] }); setChat("") }
  const reset = () => save(fresh())
  const allowed = (action: Status) => (action === "funded" && role === "client") || (action === "delivered" && role === "provider") || ((action === "approved" || action === "disputed") && role === "client") || (action === "resolved" && role === "arbiter")
  const actions: Partial<Record<Status, { label: string; next: Status }[]>> = { draft: [{ label: "Fund agreement", next: "funded" }], funded: [{ label: "Submit delivery", next: "delivered" }], delivered: [{ label: "Approve & release funds", next: "approved" }, { label: "Open dispute", next: "disputed" }], disputed: [{ label: "Resolve dispute · 60% provider", next: "resolved" }] }
  const move = (next: Status) => {
    const settled = next === "approved" || next === "resolved"
    const hasNext = demo.currentMilestone < demo.amounts.length - 1
    update({ status: settled && hasNext ? "funded" : next, currentMilestone: settled && hasNext ? demo.currentMilestone + 1 : demo.currentMilestone, note: next === "delivered" ? demo.note || "Landing page, responsive implementation, and QA notes attached." : demo.note })
  }
  return <main className="mx-auto flex w-full max-w-6xl flex-col gap-8 px-4 py-8 sm:px-8 lg:px-10">
    <PageHeader eyebrow="Presentation mode" title="MilestonePay demo" description="The full agreement path runs locally in this browser: no wallet extension, chain transaction, Arkiv write, or Swarm access." actions={<Badge variant="outline" className="border-primary/30 bg-primary/10 text-primary">MilestonePay Demo Chain · #1042</Badge>} />
    <Card className="border-primary/20 bg-primary/[0.03]"><CardContent className="grid gap-3 py-4 sm:grid-cols-3">{(Object.keys(wallets) as Role[]).map((key) => <button key={key} onClick={() => selectRole(key)} className={`rounded-lg border p-3 text-left transition-colors focus-visible:ring-2 focus-visible:ring-ring focus-visible:outline-none ${role === key ? "border-primary bg-primary/10" : "border-border hover:bg-muted/50"}`}><p className="text-sm font-medium">{wallets[key].name}</p><WalletAddress address={wallets[key].address} className="mt-1 block" />{role === key && <p className="mt-2 flex items-center gap-1 text-xs text-primary"><RiCheckLine /> Active demo wallet</p>}</button>)}</CardContent></Card>
    {!demo.created ? <CreateAgreement demo={demo} update={update} create={() => update({ created: true, status: "draft" })} role={role} /> : <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_20rem]"><div className="flex flex-col gap-6"><Agreement demo={demo} role={role} move={move} allowed={allowed} actions={actions} /><Chat demo={demo} chat={chat} setChat={setChat} send={sendChat} /></div><aside className="flex flex-col gap-4"><Card size="sm"><CardHeader><CardTitle>Agreement parties</CardTitle></CardHeader><CardContent className="flex flex-col gap-3">{(Object.keys(wallets) as Role[]).map((key) => <div key={key}><p className="text-xs text-muted-foreground uppercase">{key}</p><p className="text-sm font-medium">{wallets[key].name}</p><WalletAddress address={wallets[key].address} /></div>)}</CardContent></Card><Card size="sm"><CardHeader><CardTitle>Demo controls</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">Switch wallet above to reveal each party’s permitted action. Each approved milestone advances the simulated agreement to the next one.</CardContent><CardFooter><Button variant="outline" className="w-full" onClick={reset}><RiRefreshLine data-icon="inline-start" />Reset presentation</Button></CardFooter></Card><Card size="sm"><CardContent className="flex gap-2 pt-5 text-sm text-muted-foreground"><RiShieldCheckLine className="mt-0.5 shrink-0" />Simulation only. Private keys and real protocol data never leave the browser.</CardContent></Card></aside></div>}
  </main>
}

function CreateAgreement({ demo, update, create, role }: { demo: DemoState; update: (patch: Partial<DemoState>) => void; create: () => void; role: Role }) {
  const setAmount = (index: number, value: string) => update({ amounts: demo.amounts.map((amount, item) => item === index ? value.replace(/[^\d.]/g, "") : amount) })
  return <Card className="mx-auto w-full max-w-3xl"><CardHeader><CardTitle>New agreement</CardTitle><CardDescription>Same agreement setup, using predefined demo participants. Add as many milestone amounts as you need, then select Alice to create and fund.</CardDescription></CardHeader><CardContent className="flex flex-col gap-5"><label className="flex flex-col gap-2 text-sm font-medium">Agreement title<Input value={demo.title} onChange={(event) => update({ title: event.target.value })} /></label><div className="grid gap-4 sm:grid-cols-2"><label className="flex flex-col gap-2 text-sm font-medium">Provider wallet<Input value={wallets.provider.address} readOnly /></label><label className="flex flex-col gap-2 text-sm font-medium">Arbiter wallet<Input value={wallets.arbiter.address} readOnly /></label></div><div className="flex flex-col gap-3">{demo.amounts.map((amount, index) => <label key={index} className="flex items-center gap-3 text-sm font-medium">Milestone {index + 1} · Demo USDT<Input className="flex-1" inputMode="decimal" value={amount} onChange={(event) => setAmount(index, event.target.value)} />{demo.amounts.length > 1 && <Button type="button" variant="ghost" size="sm" onClick={() => update({ amounts: demo.amounts.filter((_, item) => item !== index) })}>Remove</Button>}</label>)}<Button type="button" variant="outline" className="w-fit" onClick={() => update({ amounts: [...demo.amounts, ""] })}><RiAddLine data-icon="inline-start" />Add milestone</Button></div></CardContent><CardFooter className="justify-end border-t"><Button disabled={role !== "client" || demo.amounts.some((amount) => !Number(amount)) || !demo.title.trim()} onClick={create}><RiAddLine data-icon="inline-start" />Create demo agreement</Button></CardFooter></Card>
}

function Agreement({ demo, role, move, allowed, actions }: { demo: DemoState; role: Role; move: (next: Status) => void; allowed: (next: Status) => boolean; actions: Partial<Record<Status, { label: string; next: Status }[]>> }) { const total = demo.amounts.reduce((sum, amount) => sum + Number(amount || 0), 0); return <Card><CardHeader><CardTitle>{demo.title}</CardTitle><CardDescription>Escrow #DEMO-1042 · {demo.amounts.length} milestones · simulated agreement</CardDescription></CardHeader><CardContent className="flex flex-col gap-5"><div className="flex flex-wrap items-center justify-between gap-3 rounded-lg border bg-muted/30 p-4"><div><p className="text-sm text-muted-foreground">Agreement value</p><Amount value={total} /></div><Badge variant={demo.status === "disputed" ? "destructive" : "outline"}>{statusLabel[demo.status]}</Badge></div><div className="grid gap-3 sm:grid-cols-2">{demo.amounts.map((amount, index) => <div key={index} className={`rounded-lg border p-3 ${index === demo.currentMilestone ? "border-primary bg-primary/10" : index < demo.currentMilestone ? "border-primary/30 bg-primary/5" : "border-border"}`}><p className="text-xs text-muted-foreground">Milestone {index + 1}{index === demo.currentMilestone ? " · current" : index < demo.currentMilestone ? " · released" : " · pending"}</p><Amount value={amount || 0} /></div>)}</div>{demo.status === "delivered" && <p className="rounded-lg border bg-muted/30 p-3 text-sm">Provider delivery: {demo.note}</p>}{demo.status === "disputed" && <p className="rounded-lg border border-destructive/30 bg-destructive/5 p-3 text-sm">The client disputed milestone {demo.currentMilestone + 1}. Switch to Cora to resolve the simulated case.</p>}{demo.status === "approved" && <p className="rounded-lg border border-primary/30 bg-primary/5 p-3 text-sm">All milestone funds released to Bruno. Agreement complete.</p>}{demo.status === "resolved" && <p className="rounded-lg border border-primary/30 bg-primary/5 p-3 text-sm">Cora settled the final dispute: 60% to Bruno, 40% returned to Alice.</p>}<div className="flex flex-wrap gap-2">{(actions[demo.status] ?? []).map((action) => <Button key={action.next} variant={action.next === "disputed" ? "destructive" : "default"} disabled={!allowed(action.next)} onClick={() => move(action.next)}>{action.label}</Button>)}</div><p className="text-sm text-muted-foreground">Active role: <span className="font-medium text-foreground">{wallets[role].name}</span>{(actions[demo.status] ?? []).length && !actions[demo.status]?.some((action) => allowed(action.next)) ? " — select the authorised demo wallet to continue." : ""}</p></CardContent></Card> }

function Chat({ demo, chat, setChat, send }: { demo: DemoState; chat: string; setChat: (value: string) => void; send: () => void }) { return <Card><CardHeader><CardTitle>Private chat · simulated</CardTitle><CardDescription>Message history is local to this browser for the demo.</CardDescription></CardHeader><CardContent className="flex flex-col gap-3">{demo.chats.map((message, index) => <p className="rounded-lg bg-muted/50 p-3 text-sm" key={`${message}-${index}`}>{message}</p>)}<div className="flex gap-2"><Textarea value={chat} onChange={(event) => setChat(event.target.value)} placeholder="Write a demo message" /><Button size="icon" aria-label="Send message" onClick={send}><RiMessage2Line /></Button></div></CardContent></Card> }
